### PR TITLE
fix: defer np.typing.ArrayLike annotation evaluation

### LINKED ISSUE #46: [Compatibility Issue] import miniball crashes for users with numpy<2 already installed
## Affected File

`python/miniball/__init__.py:8`

## Current Code

```python
# python/miniball/__init__.py
from ._miniball import _compute_miniball  # L1 — nanobind C extension
import numpy as np                        # L3

def miniball(points: np.typing.ArrayLike):  # L8
```

No `from __future__ import annotations` — the annotation is evaluated at import time, when the module is loaded.

## Root Cause

`np.typing.XXX` attribute access only works if:
- numpy >= 2.0 (via `__getattr__`), or
- some earlier code in the import chain has executed `import numpy.typing`

On numpy<2 without a prior `import numpy.typing`, this raises:

```
AttributeError: module 'numpy' has no attribute 'typing'. Did you mean: '_typing'?
```

## When This Triggers

The crash happens when **numpy<2 is installed and no earlier code has imported `numpy.typing`**. In miniball's case both conditions are very easy to hit:

1. **numpy<2 is common and pip won't upgrade it.** `pyproject.toml` declares `numpy` with no version constraint. A user who already has numpy<2 in their environment (numpy 1.26.4 is still widely deployed) runs `pip install miniball`; pip keeps the existing numpy and reports the install as successful.
2. **Nothing in the dependency chain rescues it.** nanobind is a C++ binding library and does not import `numpy.typing` (verified — `import nanobind` first does not help). Since miniball has no other dependencies, the only way `import miniball` survives on numpy<2 is if the user's own code happened to import `numpy.typing` (or a package like xarray / pandas>=3.0 that does) *before* miniball — which a user who just wants a miniball computation would have no reason to do.
3. **The import itself is the trigger point.** `miniball/__init__.py` line 1 loads the compiled extension, line 3 imports numpy, line 8 evaluates the annotation — the very first thing a user does, `import miniball`, is what raises the error.

Fully reproduced by building the package from source (master, v2.0.0) with nanobind and installing into clean venvs (Python 3.12):

| Scenario | Result |
|----------|--------|
| numpy 1.26.4, `import miniball` | ❌ `AttributeError: module 'numpy' has no attribute 'typing'` |
| numpy 1.26.4, `import nanobind` then `import miniball` | ❌ same crash (nanobind does not help) |
| numpy 1.26.4, `import numpy.typing` then `import miniball` | ✅ works (computation verified) |
| numpy 2.5.2, `import miniball` | ✅ works (computation verified) |

## Solution

Any one of:

1. **`from __future__ import annotations`** at the top of `__init__.py` (simplest — defers all annotations, also a free import-time win)
2. **`import numpy.typing`** before the function definition
3. **Pin `numpy>=2`** in `pyproject.toml` dependencies

## References

- NumPy 2.0 release notes — `numpy.typing` exposed as module attribute via `__getattr__`
- Similar fix: [numexpr#540](https://github.com/pydata/numexpr/issues/540)

### PR DESCRIPTION
**Pull request by xyf5432**
Fix #46 

## Problem

`import miniball` crashes on numpy < 2.0 with:

```
AttributeError: module 'numpy' has no attribute 'typing'
```

The `np.typing.ArrayLike` annotation on `miniball()` is evaluated at import time (no `from __future__ import annotations`), but on numpy 1.x `np.typing` is only accessible after an explicit `import numpy.typing`.

Since `pyproject.toml` declares `numpy` with no version constraint and pip does not upgrade pre-installed packages, any user who already has numpy < 2 installed hits this crash on the very first `import miniball`. nanobind (the only other dependency) does not rescue it.

## Fix

Add `from __future__ import annotations` at the top of `python/miniball/__init__.py`, which defers annotation evaluation (PEP 563).

## Verification

- Reproduced the crash by building from source against numpy 1.26.4
- With the fix, `import miniball` works on numpy 1.26.4 and the computation returns the correct result
- Also verified on numpy 2.5.2
- Existing test suite: 5/5 passed (`pytest python/test/`)

### CODE REVIEW

**Comment by hbf** [comment]
Thank you!
